### ISSUE TITLE
user inactive error

### ISSUE THREAD

**Issue by 5l1v3r1** [mibeh/VTDownloader#1]
python3 vtdownloader.py -q submitter:BR submitter:web fs:2019-08-25+ fs:2019-09-25- -n 5
03/27/2020 11:35:37 - INFO: [*] Now getting results for the query 'submitter:BR submitter:web fs:2019-08-25+ fs:2019-09-25-'.
03/27/2020 11:35:37 - INFO: [*] Sending search request to VirusTotal.
03/27/2020 11:35:38 - INFO: [-] Error:UserNotActiveError Message: User is inactive

added private api but this problem occurs

**Comment by mibeh** [comment]
Hi @5l1v3r1 , thanks for checking out this project. I've confirmed that the project is indeed working. The error you are receiving is because `The user account is not active. Make sure you properly activated your account by following the link sent to your email.` which would indicate that your VT user account is not properly activated. For reference: https://developers.virustotal.com/v3.0/reference#errors
